# Permalinks
permalink:        /:year/:month/:title/

# Setup
title:            Alex Bilbie
tagline:          'Freelance AWS Solutions Architect and Devops Consultant'
description:      'Freelance AWS Solutions Architect and Devops Consultant'
url:              http://localhost:4000

author:
  name:           'Alex Bilbie'
  url:            https://twitter.com/alexbilbie

paginate:         5
plugins:             [jekyll-paginate, jekyll-gist, jekyll-sitemap]
