# Permalinks
permalink:        /:year/:month/:title/

# Setup
title:            Alex Bilbie
tagline:          'Independent Software Developer'
description:      'Independent Software Developer'
url:              http://localhost:4000

author:
  name:           'Alex Bilbie'
  url:            https://twitter.com/alexbilbie

paginate:         5
gems:             [jekyll-paginate, jekyll-gist, jekyll-sitemap]
